[2025-05-28T10:03:19.225+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_csv_to_sqlite.load_task scheduled__2025-05-27T00:00:00+00:00 [queued]>
[2025-05-28T10:03:19.235+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_csv_to_sqlite.load_task scheduled__2025-05-27T00:00:00+00:00 [queued]>
[2025-05-28T10:03:19.236+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-28T10:03:19.249+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_task> on 2025-05-27 00:00:00+00:00
[2025-05-28T10:03:19.256+0000] {standard_task_runner.py:60} INFO - Started process 240 to run task
[2025-05-28T10:03:19.260+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_csv_to_sqlite', 'load_task', 'scheduled__2025-05-27T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/etl_csv_to_sqlite.py', '--cfg-path', '/tmp/tmpn9ascmnt']
[2025-05-28T10:03:19.263+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask load_task
[2025-05-28T10:03:19.323+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_csv_to_sqlite.load_task scheduled__2025-05-27T00:00:00+00:00 [running]> on host f1bd559e8a8b
[2025-05-28T10:03:19.403+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_csv_to_sqlite' AIRFLOW_CTX_TASK_ID='load_task' AIRFLOW_CTX_EXECUTION_DATE='2025-05-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-27T00:00:00+00:00'
[2025-05-28T10:03:19.677+0000] {python.py:201} INFO - Done. Returned value was: Data loaded successfully to SQLite. 5 records inserted in /opt/***/data/etl_database.db
[2025-05-28T10:03:19.698+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_csv_to_sqlite, task_id=load_task, execution_date=20250527T000000, start_date=20250528T100319, end_date=20250528T100319
[2025-05-28T10:03:19.718+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-28T10:03:19.732+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
